/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MedicinesRouteImport } from './routes/medicines'
import { Route as LabTestsRouteImport } from './routes/lab-tests'
import { Route as FindDoctorsRouteImport } from './routes/find-doctors'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const MedicinesRoute = MedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => rootRouteImport,
} as any)
const LabTestsRoute = LabTestsRouteImport.update({
  id: '/lab-tests',
  path: '/lab-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const FindDoctorsRoute = FindDoctorsRouteImport.update({
  id: '/find-doctors',
  path: '/find-doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/find-doctors': typeof FindDoctorsRoute
  '/lab-tests': typeof LabTestsRoute
  '/medicines': typeof MedicinesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/find-doctors': typeof FindDoctorsRoute
  '/lab-tests': typeof LabTestsRoute
  '/medicines': typeof MedicinesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/find-doctors': typeof FindDoctorsRoute
  '/lab-tests': typeof LabTestsRoute
  '/medicines': typeof MedicinesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/emergency'
    | '/find-doctors'
    | '/lab-tests'
    | '/medicines'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/emergency'
    | '/find-doctors'
    | '/lab-tests'
    | '/medicines'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/emergency'
    | '/find-doctors'
    | '/lab-tests'
    | '/medicines'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EmergencyRoute: typeof EmergencyRoute
  FindDoctorsRoute: typeof FindDoctorsRoute
  LabTestsRoute: typeof LabTestsRoute
  MedicinesRoute: typeof MedicinesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/medicines': {
      id: '/medicines'
      path: '/medicines'
      fullPath: '/medicines'
      preLoaderRoute: typeof MedicinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-tests': {
      id: '/lab-tests'
      path: '/lab-tests'
      fullPath: '/lab-tests'
      preLoaderRoute: typeof LabTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-doctors': {
      id: '/find-doctors'
      path: '/find-doctors'
      fullPath: '/find-doctors'
      preLoaderRoute: typeof FindDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EmergencyRoute: EmergencyRoute,
  FindDoctorsRoute: FindDoctorsRoute,
  LabTestsRoute: LabTestsRoute,
  MedicinesRoute: MedicinesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
